name: Run Unit Tests
on: push
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

        