name: Run Unit Tests
on: push
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Create Secrets file
        run: touch src/services/apikey.ts
      - name: Add API key
        uses: "DamianReeves/write-file-action@master"
        with:
          path: src/services/apikey.ts
          write-mode: preserve
          contents: |
          export const apikey: string = ${{secrets.API_KEY}}
      - name: Run unit tests
        run: npm run test

        