name: Run Unit Tests
on: push
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run unit tests
        env:
          REACT_APP_MOVIEDB_API_KEY: ${{secrets.API_KEY}}
        run: npm run test

        