name: Run Unit Tests
on: push
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: "Create env file"
        run: |
          touch .env
          echo MOVIEDB_API_KEY=${{secrets.API_KEY}}
          cat .env
      - name: Run unit tests
        run: npm run test

        