name: Run Unit Tests
on: push
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

        